version: "3"
services:
  talks: 
      container_name: talks
      image: webdevops/php-apache-dev:alpine
      ports: 
        - 82:80
      volumes: 
        - "./../talks/:/app"
      working_dir: "/app"
      networks: 
        - redevistoria
networks:
  redevistoria: